### ISSUE TITLE
regarding deltas

### ISSUE THREAD

**Issue by Sarah1407** [chaolongwang/SAPHIRE#3]
Hellow Dr Degang Wu,
In your code results, deltas 3 and 4  were all negative, and when I used the logit (r12) = log(r/1-r)  + delta3_5, I got negative values. I will be thankful if you can explain this to me or provide the code that calculates r1_5 values.

Many thanks for considering my request.
Sarah

**Comment by dwuab** [comment]
I'm not sure if I understand your question completely.
r is the ascertainment rate, which is a number between 0 and 1. Suppose r is the ascertainment rate in the last stage, r' is the ascertainment rate in the current stage, then according to our parametrization:

logit(r')=logit(r)+delta

and if we solve for r', we will get

r'=(1+(1-r)/(r exp(delta))^-1

so that r' is always positive as long as r is strictly between 0 and 1.

I have no idea what delta3_5 meant in your question, and what you were to calculate by using logit (r12) = log(r/1-r) + delta3_5. In our work we calculated the values of r12, r3, r4, r5, delta3, delta4 and delta5.

**Comment by Sarah1407** [comment]
Thank you, Dr Degang Wu, for answering my question.
On page 7 , you reparameterized r3,r4,and r5 by delta3,delta 4 and delta 5 according to 
logit(r 3 ) = logit( r12 ) + δ3
logit(r 4 ) = logit( r3) + δ4
logit(r 5) = logit( r4) + δ5
in which logit(r )= log( r/1-r) 

The code reults for these paramteres was 
(b12,b3,b4,b5,r12,delta3,delta4,delta5
1.31 (1.26 - 1.37), 0.4 (0.38 - 0.42), 0.17 (0.16 - 0.18), 0.1 (0.08 - 0.11), 0.15 (0.13 - 0.17), -0.05 (-0.15 - 0.06), -0.4 (-0.48 - -0.32), 0.58 (0.44 - 0.72))

According to this, the calculation of  r3 with 95% CI will be based on

r'=(1+(1-0.15)/(0.15 exp(-0.05))^-1

**Comment by dwuab** [comment]
Hi Sarah,

I guess your question is how to calculate the means and 95% CI boundaries of r3, r4 and r5. They cannot be calculated from `output/summary_run_*.txt`. Instead, they are calculated from `output/pars_est_run_*.txt`. In `output/pars_est_run_*.txt`, there is one set of r12, delta3, delta4, etc. for one iteration of MCMC. For instance, there are 10,000 sets of r12, delta3, etc. in the file, then for every set, you can calculate r3 from r12 and delta3 in the set, so in the end you should have 10,000 values of r3. From these 10,000 values of r3, you can calculate the means and 95% CI boundaries of r3. The same goes for r4 and r5.

**Comment by Sarah1407** [comment]
Thank you, Dr Degang Wu,
I will be grateful to you if you can send me the code you use for what you have explained above. I am not that expert in R.

Thanks though for your time and help.

**Comment by Sarah1407** [comment]
Hi Degang,
code_root="/path/to/SAPHIRE/"
setwd(paste0(code_root, "output"))
source(paste0(code_root, "R/fun_SEIRsimu.R"))
source(paste0(code_root, "R/init_cond.R"))


#############################       Predicted_infections_on_Mar8   
####################################
init_sets_list <- get_init_sets_list(r0 = 0.23)
init_sets_list$days_to_fit <- 1:68
pars_ests <- as.matrix(read.table("pars_est_run_main_analysis.txt", header = T))
pars_ests <- tail(pars_ests, 10000)
## Mar 8 / five periods
est_infect_mat <- NULL
estS <- apply(pars_ests, 1, function(x) SEIRsimu(pars = x, init_settings = init_sets_list)[68, "S"])
est_infect <- init_sets_list$N - estS
est_infect_mat <- cbind(est_infect_mat, est_infect)
#
estS <- apply(pars_ests, 1, function(x) SEIRsimu(pars = x, init_settings = init_sets_list)[68, "S"])
est_infect <- init_sets_list$N - estS
est_infect_mat <- cbind(est_infect_mat, est_infect)
...
stat_mean <- apply(est_infect_mat, 2, function(x) round(mean(x), 0))
stat_quant <- apply(est_infect_mat, 2, function(x) round(quantile(x, c(0.025, 0.975)), 0))
stat_mean
stat_quant
Could you please tell how can we calculate the means and 95% ci for r3,r4 and r5?I would appreciate you can help me ansering my question

**Comment by dwuab** [comment]
Hi Sarah,

Like I said previously, for example, in `output/pars_est_run_*.txt`, if we have
```
b12	b3	b4	b5	r12	delta3	delta4	delta5	Lposterior	Llikelihood	Lprior
1.259	0.413	0.176	0.1	0.17	-0.088	-0.423	0.634	-280.839	-276.547	-4.293
1.331	0.39	0.175	0.11	0.143	-0.073	-0.375	0.546	-276.781	-272.23	-4.551
1.277	0.403	0.175	0.1	0.159	0.022	-0.523	0.665	-285.355	-280.892	-4.463
...
```
then we can calculate according to the equations listed in the paper
```
r3	r4	r5
0.1579412	0.1094251	0.1880659
0.1342848	...	...
0.1619639	...	...
...
```
so that you have many values of r3, r4 and r5. You can calculate 95% CI from these many values of r3, r4 and r5. This is all basic statistics. There is nothing specific that can only be achieved through R. Nevertheless, I may add several lines of code to illustrate how r3, r4 and r5 could be calculated in R.

**Comment by Sarah1407** [comment]
Hi Degang, 
Thank you so much for your response. I will be grateful to you if you can do that. 
Regards,

**Comment by Fladimer** [comment]
Thanks, Degang,
Hi Degang, thank you for forwarding me to Sarah questions. As far as know, deltas in your study are the changes in r, either negative or positive. Am I right? On the other hand, Sarah had provided some code. Does that calculate r3,r4, and r5. If so that good enough for me otherwise which part of your code calculates these r3,r4 and r5.

**Comment by Suzzan-1991** [comment]
Hi Degang, 
Thank you for forwarding me to Sarah questions. As far as know, deltas in your study are the changes in r, either negative or positive. Am I right? On the other hand, Sarah had provided some code. Does that calculate r3,r4, and r5. If so that good enough for me otherwise which part of your code calculates these r3,r4 and r5.

**Comment by Sarah1407** [comment]
Hi Fladimer,
The code I provided did not calculate r3,r4, and r5. I think Degang will add several lines of code to illustrate how r3, r4 and r5 could be calculated in R according to one of his response to me. You should double-check with him.
Best wishes,
Sarah

**Comment by Suzzan-1991** [comment]
Hi Degang,
Thank you for providing such valuable information. I got your points for estimating r3,r4, and r5 and I think you we need to close the brackets to be all to the power of -1 LIKE r'=(1+(1-r)/(r exp(delta)))^-1
, otherwise, we will end up with different results. On the other hand, Sarah mentioned that you will modify the code to illustrate the estimation of r3,r4, and r5 with a 95% confidence interval. Can you please give some hints on how to do it in R? 

Thank you for your cooperation,
Fladimer

**Comment by dwuab** [comment]
@Sarah1407 

See https://github.com/dwuab/SAPHIRE/commit/aaa777e0d99a990ca35e95099e58d9cf6c18866f as promised.

**Comment by Sarah1407** [comment]
Thanks, Dr Degang for all your help and support. I learned a lot from you.
Fladimer

**Comment by Sarah1407** [comment]
Thank you so much Degang, for charing some of your valuable time and help us.
Thanks Fladimer for sharing these questions with us

**Comment by Suzzan-1991** [comment]
Thanks to Professor Chaolong and Dr Degang for their time and help, also thanks for Sarah for responding to my question and her advice contacting you.

**Comment by Sarah1407** [comment]
Best wished
